Repository sailfishos-applications/flowplayer, pull requests merged in 2024-02, with the labels that each got.

#39 [flowplayer.spec] Add missing `BuildRequires: pkgconfig(Qt5Xml)`
  rpm/flowplayer.spec
Labels: bug

#37 [AboutPage.qml] Adopt changes from FileCase's `AboutPage.qml`
  qml/pages/AboutPage.qml
  translations/flowplayer.ts
Labels: documentation

#33 Use Sailfish.Pickers.FolderPickerPage to configure music directories
  FlowPlayer.pro
  qml/pages/ManageFolders.qml
  qml/pages/PickFolder.qml
  src/FlowPlayer.cpp
Labels: enhancement

#52 Remove `migrating-to-v0.3.x.md`
  README.md
  migrating-to-v0.3.x.md
Labels: documentation

#53 `devel`→`master`: commits for v0.3.2
  FlowPlayer.pro
  README.md
  qml/pages/AboutPage.qml
  qml/pages/AddFolder.qml
  qml/pages/AlbumListView.qml
  qml/pages/AlbumMetadata.qml
  qml/pages/ManageFolders.qml
  qml/pages/NowPlaying.qml
  qml/pages/PickFolder.qml
  qml/pages/SongsPage.qml
  rpm/flowplayer.changes
  rpm/flowplayer.spec
  src/FlowPlayer.cpp
  src/coversearch.cpp
  src/datareader.cpp
  src/datos.cpp
  src/lfm.cpp
  src/meta.cpp
  src/musicmodel.cpp
  src/player.cpp
  src/playlist.cpp
  src/playlistmanager.cpp
  src/utils.cpp
  translations/de.ts
  translations/flowplayer.ts
  translations/sv.ts
Labels: enhancement

#54 Rectify changelog
  rpm/flowplayer.changes
Labels: documentation

#56 [flowplayer.changes] Fix day of the week
  rpm/flowplayer.changes
  rpm/flowplayer.spec
Labels: bug

#57 [flowplayer.changes] Fix day of the week (#56)
  rpm/flowplayer.changes
  rpm/flowplayer.spec
Labels: bug, documentation
